# Generated by Django 5.0.6 on 2025-08-23 21:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('kpi', 'KPI Summary'), ('electrical', 'Electrical Metrics'), ('production', 'Production Analysis'), ('consumption', 'Consumption Analysis'), ('comprehensive', 'Comprehensive Report')], max_length=20)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('md', 'Markdown'), ('csv', 'CSV')], max_length=10)),
                ('include_charts', models.BooleanField(default=True)),
                ('date_range', models.CharField(choices=[('today', 'Today'), ('yesterday', 'Yesterday'), ('last_7_days', 'Last 7 Days'), ('last_30_days', 'Last 30 Days'), ('this_month', 'This Month'), ('custom', 'Custom')], default='last_7_days', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.reportconfiguration')),
            ],
        ),
    ]
