# Generated by Django 5.2.5 on 2025-08-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MicrogridData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("battery_active_power", models.FloatField(blank=True, null=True)),
                (
                    "battery_active_power_set_response",
                    models.FloatField(blank=True, null=True),
                ),
                ("pvpcs_active_power", models.FloatField(blank=True, null=True)),
                ("ge_body_active_power", models.FloatField(blank=True, null=True)),
                ("ge_active_power", models.FloatField(blank=True, null=True)),
                (
                    "ge_body_active_power_set_response",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "fc_active_power_fc_end_set",
                    models.FloatField(blank=True, null=True),
                ),
                ("fc_active_power", models.FloatField(blank=True, null=True)),
                (
                    "fc_active_power_fc_end_set_response",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "island_mode_mccb_active_power",
                    models.FloatField(blank=True, null=True),
                ),
                ("mg_lv_msb_ac_voltage", models.FloatField(blank=True, null=True)),
                (
                    "receiving_point_ac_voltage",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "island_mode_mccb_ac_voltage",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "island_mode_mccb_frequency",
                    models.FloatField(blank=True, null=True),
                ),
                ("mg_lv_msb_frequency", models.FloatField(blank=True, null=True)),
                (
                    "inlet_temperature_of_chilled_water",
                    models.FloatField(blank=True, null=True),
                ),
                ("outlet_temperature", models.FloatField(blank=True, null=True)),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
    ]
