services:
  web:
    build:
      context: ./backend  
      dockerfile: Dockerfile
    command: gunicorn microgrid_monitoring.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles
      - csv_uploads:/app/csv_uploads
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    
  celery-worker:
    build:
      context: ./backend  
      dockerfile: Dockerfile
    command: celery -A microgrid_monitoring worker --loglevel=info
    volumes:
      - ./backend:/app
      - csv_uploads:/app/csv_uploads
    depends_on:
      - redis
      - web
    env_file: .env


  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles
      - csv_uploads:/app/csv_uploads
    depends_on:
      - web
      - celery-worker

volumes:
  postgres_data:
  static_volume:
  csv_uploads: